### ISSUE TITLE
QueryDSL SQL 4.1.0

### ISSUE THREAD

**Issue by natros** [vineey/archelix-rsql#13]
Hello,

You have here a very interesting project that I would like to use. My question is, does it work with last version of QueryDSL SQL 4.1.0?

Thank you.

**Comment by vineey** [comment]
@natros  Not yet tested. But theoretically, I'm just using querydsl-core so it should automatically support it since practically, the code is not specific only to mongodb or jpa model.

Its just that currently my unit tests only include jpa and mongodb, but will add unit tests for querydsl sql as well. Will include your request in M2 release, probably be completed this late April.

Anyway, you can try M1 release to see if it works, then please let me know. But please expect that M1 release API could change its signature so it is not production ready. 1.0.0.RELEASE is tentatively to be completed on later May 2016.

**Comment by vineey** [comment]
@natros  I saw the new Querydsl 4.x.x and it has entirely new java packages and class names.

[Upgrading Querydsl 3 to 4](http://blog.anthavio.net/2015/11/upgrading-querydsl-3-to-4.html)

Will defer the decision for support on 1.0.0.M3

**Comment by vineey** [comment]
Hi @natros, just want to inform you a good news. I'm planning to create a 2.0.0 release concurrently with 1.0.0 release. As I've seen, the latest querydsl groupId is caused by the change of the company owner of the product. So this means, 4.x.x structure will be followed from now on, and 3.x.x will be sort of legacy code. So as much possible, my library must keep on updated with the latest querydsl library. This is why, I am going to simultaneously create another branch for 3.x.x separately, and 4.x.x will be the main code which stays on develop branch. The final releases(1.0.0 and 2.0.0) are approximately will be delivered on later part of May 2016.

Please feel free to offer any assistance, any help is greatly appreciated.

**Comment by natros** [comment]
That's good news. I believe querydsl is fallowing the same release model. I can offer my assistance with migration but I'm a newcomer to querydsl.

**Comment by vineey** [comment]
@natros Hi good news again, 1.0.0.RELEASE is completed and deployed to maven central. 
If you have time and want to help, you can fork this repo and checkout git branch 'feature/querydsl4'.
From this branch you can start to migrate the code from using querydsl 3.x.x to querydsl 4.x.x. This will be the branch where 2.0.0.RELEASE would be built.  If you are familiar with maven or gradle, then it will be easier. Let me know if you agree and if you still need more information. Migration only takes time but not that hard, and since I have a full time job and also a husband and a father, its time that I don't really that have much. That's why any assistance is greatly appreciated.

**Comment by vineey** [comment]
@natros Hi natros, have you think about helping me on this one? If you are currently working on it, AWESOME!  Just continue it on your pace and I will assign the ticket to you. Else just let me know as well so I can own this one.

Please don't hesitate to send me a message if you have any questions. Here is my personal email, vinetech416@gmail.com. 

Or we can start the discussion here in gitter, https://gitter.im/vineey/rsqlQuerydsl
You can login via github OAuth.

**Comment by wwadge** [comment]
See : https://github.com/vineey/archelix-rsql/pull/16

**Comment by natros** [comment]
Hi @vineey sorry to disappoint you. I have two jobs and lately I have no free time to spare. I had started the migration before opening the issue, only the testes where not converted.

**Comment by vineey** [comment]
@natros no problem, I understand, we have the same situation. Still, thank you for starting the idea and the time. Don't worry, another interested developer has already submitted a pull request for querydsl v4.x.x migration.

**Comment by vineey** [comment]
fix on issue #16

**Comment by vineey** [comment]
Will deploy on osshr for maven release at the end of this day. Just need to updates test and code cleanup to increase code quality.

Thanks @natros for pointing me on this direction!

Thanks @wwadge for the great contribution.

I will make sure your efforts are listed in the release notes. Please always feel free to give suggestions and contributions on tasks for this project milestones. Thanks guys!
